version: '3.9'

services:
  mongo:
    image: mongo:7.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - .\mongodata:/data/db
